"""memory v2 tables

Revision ID: dccb397a0b8d
Revises: 
Create Date: 2026-08-08 00:35:46.738100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dccb397a0b8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_events',
    sa.Column('event_id', sa.CHAR(length=36, collation='ascii_bin'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('memory_id', sa.CHAR(length=36, collation='ascii_bin'), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('related_memory_id', sa.CHAR(length=36, collation='ascii_bin'), nullable=True),
    sa.Column('source_thread_id', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("actor_type IN ('user','system','admin')", name='ck_memory_events_actor_type'),
    sa.CheckConstraint("event_type IN ('created','updated','superseded','forgotten')", name='ck_memory_events_event_type'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_memory_events_memory_created', 'memory_events', ['memory_id', 'created_at'], unique=False)
    op.create_index('ix_memory_events_user_created', 'memory_events', ['user_id', 'created_at'], unique=False)
    op.create_table('memory_items',
    sa.Column('memory_id', sa.CHAR(length=36, collation='ascii_bin'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_thread_id', sa.String(length=255), nullable=False),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('fingerprint', sa.CHAR(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('active_fingerprint', sa.CHAR(length=64, collation='ascii_bin'), sa.Computed("CASE WHEN status='active' THEN fingerprint ELSE NULL END", persisted=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.CheckConstraint("entity_type IS NULL OR entity_type IN ('supplier','material','order')", name='ck_memory_items_entity_type'),
    sa.CheckConstraint("kind IN ('supplier_context','procurement_constraint','task_outcome','user_feedback')", name='ck_memory_items_kind'),
    sa.CheckConstraint("source_type IN ('user_explicit','tool_verified','model_inferred')", name='ck_memory_items_source_type'),
    sa.CheckConstraint("status IN ('active','superseded','forgotten')", name='ck_memory_items_status'),
    sa.CheckConstraint('CHAR_LENGTH(content) BETWEEN 1 AND 2000', name='ck_memory_items_content_length'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at >= created_at', name='ck_memory_items_time_order'),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('user_id', 'active_fingerprint', name='uq_memory_items_user_active_fingerprint')
    )
    op.create_index('ix_memory_items_expires_status', 'memory_items', ['expires_at', 'status'], unique=False)
    op.create_index('ix_memory_items_user_entity', 'memory_items', ['user_id', 'entity_type', 'entity_id', 'status'], unique=False)
    op.create_index('ix_memory_items_user_status_kind_updated', 'memory_items', ['user_id', 'status', 'kind', 'updated_at'], unique=False)
    op.create_table('memory_jobs',
    sa.Column('job_id', sa.CHAR(length=36, collation='ascii_bin'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255, collation='ascii_bin'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('locked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("job_type IN ('extract_memory','expire_memory')", name='ck_memory_jobs_job_type'),
    sa.CheckConstraint("status IN ('pending','processing','succeeded','failed','dead','cancelled')", name='ck_memory_jobs_status'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_memory_jobs_status_available_locked', 'memory_jobs', ['status', 'available_at', 'locked_at'], unique=False)
    op.create_table('memory_profiles',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('schema_version', mysql.SMALLINT(unsigned=True), server_default=sa.text('2'), nullable=False),
    sa.Column('version', mysql.BIGINT(unsigned=True), server_default=sa.text('1'), nullable=False),
    sa.Column('output_format', sa.String(length=32), nullable=True),
    sa.Column('chart_type', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('language', sa.String(length=35), nullable=True),
    sa.Column('procurement_defaults', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint('schema_version >= 2', name='ck_memory_profiles_schema_version'),
    sa.CheckConstraint("output_format IS NULL OR output_format IN ('text','table','json')", name='ck_memory_profiles_output_format'),
    sa.CheckConstraint("chart_type IS NULL OR chart_type IN ('bar','line','pie','none')", name='ck_memory_profiles_chart_type'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('memory_user_state',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('memory_revision', mysql.BIGINT(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('memory_generation', mysql.BIGINT(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_user_state')
    op.drop_table('memory_profiles')
    op.drop_index('ix_memory_jobs_status_available_locked', table_name='memory_jobs')
    op.drop_table('memory_jobs')
    op.drop_index('ix_memory_items_user_status_kind_updated', table_name='memory_items')
    op.drop_index('ix_memory_items_user_entity', table_name='memory_items')
    op.drop_index('ix_memory_items_expires_status', table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index('ix_memory_events_user_created', table_name='memory_events')
    op.drop_index('ix_memory_events_memory_created', table_name='memory_events')
    op.drop_table('memory_events')
    # ### end Alembic commands ###
